CREATE TABLE [Utils].[Error]
(
  [Id] INT NOT NULL IDENTITY(1,1)
  , [EventDateTime] DATETIME2 NOT NULL CONSTRAINT [DF_Error_DateTime] DEFAULT GETDATE()
  , [Source] SYSNAME NOT NULL
  , [Error] NVARCHAR(MAX) NOT NULL
  , CONSTRAINT [PK_Error_Id] PRIMARY KEY CLUSTERED ([Id])
)
